const crypto = require('crypto');
const { TelegramConnection } = require('../models');

const TELEGRAM_API = 'https://api.telegram.org';
const CODE_TTL_MS = 10 * 60 * 1000;

const getToken = () => process.env.TELEGRAM_BOT_TOKEN;
const hashCode = (code) => crypto.createHash('sha256').update(code).digest('hex');

const telegramRequest = async (method, payload, timeoutMs = 8000) => {
  const token = getToken();
  if (!token) {
    throw new Error('TELEGRAM_BOT_TOKEN is not configured');
  }

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  let response;
  try {
    response = await fetch(`${TELEGRAM_API}/bot${token}/${method}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: controller.signal
    });
  } finally {
    clearTimeout(timeoutId);
  }
  const data = await response.json();
  if (!response.ok || !data.ok) {
    throw new Error(data.description || `Telegram API request failed: ${response.status}`);
  }
  return data.result;
};

const createConnectionCode = async (businessId) => {
  const code = `BILLING-${crypto.randomInt(100000, 1000000)}`;
  await TelegramConnection.findOneAndUpdate(
    { businessId },
    {
      connectionCodeHash: hashCode(code),
      connectionCodeExpiresAt: new Date(Date.now() + CODE_TTL_MS),
      enabled: true
    },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );
  return { code, expiresAt: new Date(Date.now() + CODE_TTL_MS) };
};

const getConnection = (businessId) => TelegramConnection.findOne({ businessId }).lean();

const disconnect = async (businessId) => {
  await TelegramConnection.findOneAndUpdate(
    { businessId },
    { $unset: { chatId: 1, connectionCodeHash: 1, connectionCodeExpiresAt: 1 } }
  );
};

const sendMessage = async (chatId, text) => telegramRequest('sendMessage', {
  chat_id: chatId,
  text,
  disable_web_page_preview: true
});

const notifyLowStock = async (businessId, product, previousStock) => {
  if (product.stock > product.minStockLevel || previousStock <= product.minStockLevel) return;
  const connection = await TelegramConnection.findOne({
    businessId,
    enabled: true,
    lowStockAlertsEnabled: true,
    chatId: { $exists: true, $ne: null }
  });
  if (!connection) return;

  await sendMessage(connection.chatId, [
    '⚠️ LOW STOCK ALERT / ALERTA DE STOCK BAJO',
    '',
    '🇬🇧 English',
    `Product: ${product.name}`,
    `Current stock: ${product.stock}`,
    `Minimum stock: ${product.minStockLevel}`,
    'Action: Please restock this product.',
    '',
    '🇪🇸 Español',
    `Producto: ${product.name}`,
    `Stock actual: ${product.stock}`,
    `Stock mínimo: ${product.minStockLevel}`,
    'Acción: Reponer este producto.',
  ].join('\n'));
  connection.lastAlertAt = new Date();
  await connection.save();
};

const processUpdate = async (update) => {
  const message = update.message;
  const text = message?.text?.trim();
  const chatId = message?.chat?.id;
  if (!text || !chatId) return;

  const code = text.replace(/^\/start\s*/i, '').trim().toUpperCase();
  if (!/^BILLING-\d{6}$/.test(code)) {
    if (/^\/start$/i.test(text)) {
      await sendMessage(chatId, 'Send the connection code generated by your inventory system.');
    }
    return;
  }

  const connection = await TelegramConnection.findOne({
    connectionCodeHash: hashCode(code),
    connectionCodeExpiresAt: { $gt: new Date() }
  });
  if (!connection) {
    await sendMessage(chatId, 'This connection code is invalid or expired.');
    return;
  }

  connection.chatId = String(chatId);
  connection.connectionCodeHash = undefined;
  connection.connectionCodeExpiresAt = undefined;
  await connection.save();
  await sendMessage(chatId, 'Telegram notifications connected successfully.');
};

let polling = false;
let offset = 0;
const pollUpdates = async () => {
  if (polling || !getToken()) return;
  polling = true;
  try {
    const updates = await telegramRequest(
      'getUpdates',
      { offset, timeout: 25, allowed_updates: ['message'] },
      35000
    );
    for (const update of updates) {
      offset = update.update_id + 1;
      await processUpdate(update);
    }
  } catch (error) {
    console.error('[Telegram] polling error:', error.message);
  } finally {
    polling = false;
    if (getToken()) setTimeout(pollUpdates, 1000);
  }
};

const startPolling = () => {
  if (getToken()) pollUpdates();
};

module.exports = {
  createConnectionCode,
  getConnection,
  disconnect,
  notifyLowStock,
  startPolling
};
