from __future__ import annotations

import json
import shutil
import unittest
import uuid
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.dummy import DummyRegressor
from sklearn.pipeline import Pipeline

from ml.src.common import sha256_file
from ml.src.inference.demand_v1 import (
    CATEGORICAL_FEATURES,
    build_feature_contract,
    predict_demand7d,
    validate_and_order_features,
)
from ml.src.training.refit_final_model import (
    EXPECTED_REFIT_ROWS,
    REFIT_SPLITS,
    validate_metadata,
)
from ml.src.training.train_hgb_sample import build_hgb_preprocessor


FEATURES = ["current_units", *CATEGORICAL_FEATURES]
DTYPES = {name: "VARCHAR" for name in CATEGORICAL_FEATURES} | {
    "current_units": "INTEGER"
}


def fixture() -> pd.DataFrame:
    return pd.DataFrame(
        {
            "current_units": [1.0, 2.0, 3.0, 4.0],
            "cat_id": ["A", "A", "B", "B"],
            "dept_id": ["D1", "D1", "D2", "D2"],
            "event_name_1": ["__NONE__"] * 4,
            "event_type_1": ["__NONE__"] * 4,
            "event_name_2": ["__NONE__"] * 4,
            "event_type_2": ["__NONE__"] * 4,
        }
    )


class R4DContractTests(unittest.TestCase):
    def setUp(self) -> None:
        self.contract = build_feature_contract(FEATURES, DTYPES)

    def test_contract_is_strict_ordered_and_complete(self) -> None:
        self.assertTrue(self.contract["strict"])
        self.assertEqual(self.contract["feature_order"], FEATURES)
        self.assertTrue(all(entry["required"] for entry in self.contract["features"]))
        self.assertTrue(all(not entry["nullable"] for entry in self.contract["features"]))

    def test_safe_reorder_and_float32_sanitization(self) -> None:
        frame = fixture()[list(reversed(FEATURES))]
        result = validate_and_order_features(frame, self.contract)
        self.assertEqual(list(result.columns), FEATURES)
        self.assertEqual(result["current_units"].dtype, np.dtype("float32"))

    def test_missing_unexpected_null_and_nonfinite_are_rejected(self) -> None:
        with self.assertRaisesRegex(ValueError, "Missing required"):
            validate_and_order_features(fixture().drop(columns="cat_id"), self.contract)
        with self.assertRaisesRegex(ValueError, "Unexpected"):
            validate_and_order_features(fixture().assign(item_id="secret"), self.contract)
        with self.assertRaisesRegex(ValueError, "null"):
            validate_and_order_features(fixture().assign(cat_id=None), self.contract)
        with self.assertRaisesRegex(ValueError, "NaN or infinity"):
            validate_and_order_features(
                fixture().assign(current_units=np.inf), self.contract
            )

    def test_final_refit_allowlist_excludes_test(self) -> None:
        self.assertEqual(REFIT_SPLITS, ("train", "validation"))
        self.assertNotIn("test", REFIT_SPLITS)


class R4DArtifactTests(unittest.TestCase):
    def test_generated_artifact_matches_metadata_when_present(self) -> None:
        models = Path(__file__).resolve().parents[1] / "models"
        artifact = models / "demand_forecast_v1.joblib"
        metadata_path = models / "model_metadata.json"
        contract_path = models / "demand_forecast_v1_contract.json"
        if not artifact.exists():
            self.skipTest("Final artifact is generated by the ML-R4D.1 refit command")
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        contract = json.loads(contract_path.read_text(encoding="utf-8"))
        loaded = joblib.load(artifact)
        self.assertIsInstance(loaded, Pipeline)
        self.assertEqual(list(loaded.named_steps), ["preprocessing", "estimator"])
        self.assertEqual(sha256_file(artifact), metadata["joblib_sha256"])
        self.assertEqual(artifact.stat().st_size, metadata["joblib_size_bytes"])
        self.assertEqual(contract["feature_order"], metadata["feature_names"])
        validate_metadata(metadata)

    def test_pipeline_round_trip_shape_finite_clipping_and_hash(self) -> None:
        contract = build_feature_contract(FEATURES, DTYPES)
        frame = validate_and_order_features(fixture(), contract)
        preprocessor, _ = build_hgb_preprocessor(FEATURES)
        pipeline = Pipeline(
            [
                ("preprocessing", preprocessor),
                (
                    "estimator",
                    DummyRegressor(strategy="mean"),
                ),
            ]
        )
        pipeline.fit(frame, np.array([1, 2, 3, 4], dtype=np.float32))
        directory = Path(__file__).resolve().parents[1] / ".test-tmp" / f"r4d-{uuid.uuid4().hex}"
        directory.mkdir(parents=True)
        try:
            path = directory / "model.joblib"
            joblib.dump(pipeline, path, compress=3)
            digest = sha256_file(path)
            loaded = joblib.load(path)
            prediction = predict_demand7d(loaded, fixture(), contract)
            self.assertEqual(len(digest), 64)
            self.assertEqual(prediction.shape, (4,))
            self.assertTrue(np.isfinite(prediction).all())
            self.assertTrue((prediction >= 0).all())
        finally:
            shutil.rmtree(directory, ignore_errors=True)

    def test_metadata_validator_requires_provenance(self) -> None:
        metadata = {
            "model_name": "demand_forecast_v1",
            "model_version": "1.0.0",
            "feature_set_version": "demand-v1",
            "training_policy": "train_plus_validation_after_single_final_test",
            "refit_rows": EXPECTED_REFIT_ROWS,
            "test_rows": 255_989,
            "joblib_sha256": "0" * 64,
            "feature_names": [f"f{index}" for index in range(31)],
            "hyperparameters": {},
            "final_test_metrics": {},
        }
        validate_metadata(metadata)
        del metadata["joblib_sha256"]
        with self.assertRaisesRegex(ValueError, "incomplete"):
            validate_metadata(metadata)


if __name__ == "__main__":
    unittest.main()
